language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
script:
  - "pytest --cov-report=term-missing --cov=fbdata tests"
after_success:
  - coveralls